// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3DNPY4lYO6FiaKpOmmCBbytA2iy2G8RA',
    appId: '1:831830146465:web:ee0e837a60cea95a175fe0',
    messagingSenderId: '831830146465',
    projectId: 'bawangmerahapp1',
    authDomain: 'bawangmerahapp1.firebaseapp.com',
    databaseURL: 'https://bawangmerahapp1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bawangmerahapp1.appspot.com',
    measurementId: 'G-5JDWS6FWF9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD36DAwZ1TcF-3PVnrnW6PCugLZB1rhkus',
    appId: '1:831830146465:android:89fd14ba196ade2f175fe0',
    messagingSenderId: '831830146465',
    projectId: 'bawangmerahapp1',
    databaseURL: 'https://bawangmerahapp1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bawangmerahapp1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCQgYOynV3fYVz8tPU5U-pdq_RtvLnkBY',
    appId: '1:831830146465:ios:44bd91fc12925b59175fe0',
    messagingSenderId: '831830146465',
    projectId: 'bawangmerahapp1',
    databaseURL: 'https://bawangmerahapp1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bawangmerahapp1.appspot.com',
    iosBundleId: 'com.example.bawangmerahapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCQgYOynV3fYVz8tPU5U-pdq_RtvLnkBY',
    appId: '1:831830146465:ios:2e25532884d89242175fe0',
    messagingSenderId: '831830146465',
    projectId: 'bawangmerahapp1',
    databaseURL: 'https://bawangmerahapp1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bawangmerahapp1.appspot.com',
    iosBundleId: 'com.example.bawangmerahapp.RunnerTests',
  );
}
